/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test.java.codeForHorizon;

import org.testng.annotations.*;

import main.java.codeForHorizon.App;

import static org.testng.Assert.*;

import java.io.FileNotFoundException;

public class AppTest {
    @Test public void appForFileProcess() throws FileNotFoundException {
        App classUnderTest = new App();
        classUnderTest.fileProcessing();
    }
}
